export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

//RootLayoutは、HTMLのテンプレートを出力するためのコンポーネント
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
